---
dist: bionic
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - spec
matrix:
  include:
    -
      env: CHECK="rubocop"
      stage: spec
    -
      env: CHECK="rspec"
      stage: spec
branches:
  only:
    - master
